### ISSUE TITLE
2dassess 1.0.0 fails

### ISSUE THREAD

**Issue by azazellochg** [cianfrocco-lab/Automatic-cryoEM-preprocessing#22]
```
Assessing 2D class averages....
Traceback (most recent call last):
  File "/home/azazello/soft/miniconda3/envs/cryoassess-1.0.0/bin/2dassess", line 33, in <module>
    sys.exit(load_entry_point('cryoassess', 'console_scripts', '2dassess')())
  File "/home/azazello/soft/scipion3/software/em/cryoassess-1.0.0/cryoassess-master/cryoassess/assess2d.py", line 119, in main
    predict(args)
  File "/home/azazello/soft/scipion3/software/em/cryoassess-1.0.0/cryoassess-master/cryoassess/assess2d.py", line 73, in predict
    model.compile(optimizer = Adam(lr = 1e-4), loss = ncce, metrics = [metrics.categorical_accuracy])
NameError: name 'Adam' is not defined
```

**Comment by yilaili** [comment]
Thanks for reporting this. We didn't update 2dassess and I assume this is due to the dependency update in the new version. I will fix this and let you know.

**Comment by yilaili** [comment]
I have fixed the bug. Please test again when you have time. Thanks again!

**Comment by azazellochg** [comment]
Thanks a lot, it works now!
